services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
    - "5005:5005"
    command: php artisan serve --host=0.0.0.0 --port=5005
    depends_on:
      - db
    networks:
      - laravel-net

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    environment:
      - NUXT_PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - laravel-net

volumes:
  dbdata:

networks:
  laravel-net:
    driver: bridge

