services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /var/www
    ports:
    - "5005:5005"
    command: php artisan serve --host=0.0.0.0 --port=5005
    networks:
      - laravel-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    environment:
      - NUXT_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - laravel-net


networks:
  laravel-net:
    driver: bridge

