version: "3.8"

services:
  backend:
    image: moha210/backend:latest
    expose:
      - "5005"
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure

  frontend:
    image: moha210/frontend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: overlay
