version: "3.8"

services:
  backend:
    image: moha210/backend:latest
    ports:
      - "5005:5005"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    environment:
      - NUXT_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - laravel-net
networks:
  laravel-net:
    driver: bridge

