version: "3.8"

services:
  backend:
    image: moha210/backend:latest
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure
    env_file:
      - /root/arises/backend/.env

  frontend:
    image: moha210/frontend:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: on-failure