services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /var/www
    ports:
    - "5005:5005"
    command: php artisan serve --host=0.0.0.0 --port=5005
    volumes:
      - ./backend:/var/www/
    env_file:
        - ./backend/.env


