version: "3.8"

services:
  backend:
    image: moha210/backend:latest
    ports:
      - "5005:5005"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
