services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /var/www
    ports:
    - "5005:5005"
    command: php artisan serve --host=0.0.0.0 --port=5005
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - laravel-net


  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-net

volumes:
  dbdata:
  backend:

networks:
  laravel-net:
    driver: bridge

