version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /var/www
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped