apiVersion: apps/v1
kind: Deployment
metadata:
  name: arises-app
  namespace: arises
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arises
  template:
    metadata:
      labels:
        app: arises
    spec:
      containers:
      - name: frontend
        image: arises-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "http://localhost:5005"

      - name: backend
        image: arises-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 10 