apiVersion: v1
kind: Service
metadata:
  name: arises
  namespace: arises
spec:
  selector:
    app: arises
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: backend
      protocol: TCP
      port: 5005
      targetPort: 5005
  type: LoadBalancer 