name: Build & Deploy Arises

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build & Push Images to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ghcr.io/${{ env.OWNER }}/backend:latest ./backend
          docker push ghcr.io/${{ env.OWNER }}/backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ghcr.io/${{ env.OWNER }}/frontend:latest ./frontend
          docker push ghcr.io/${{ env.OWNER }}/frontend:latest

  deploy:
    name: Deploy to K3s from GitHub
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.VPS_KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Set kubectl context
        run: |
          kubectl config set-cluster default --server=https://${{ secrets.VPS_HOST }}:6443 --insecure-skip-tls-verify=true

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment backend
          kubectl rollout restart deployment frontend
