name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Simple Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd ~/arises
            git pull origin main
#            docker compose -f docker-compose.yml pull
#            docker compose -f docker-compose.yml up -d --build
